In [29]:
import pandas as pd

In [30]:
dataset=pd.read_csv('insurance_pre.csv')

In [31]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [32]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [33]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [34]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [35]:
independent= dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent= dataset[['charges']]

In [12]:
#applying standarisation
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [32]:
x_train

array([[-0.14853305,  0.54530479,  2.41394802,  1.01506676,  1.97125461],
       [-1.49780784,  0.59867181, -0.89219519,  1.01506676, -0.50729114],
       [-1.14273553,  0.96092064,  0.76087642, -0.98515688,  1.97125461],
       ...,
       [ 0.06451033, -0.91339361, -0.89219519,  1.01506676, -0.50729114],
       [-1.42679338,  0.77656186, -0.89219519,  1.01506676, -0.50729114],
       [-0.4325909 , -1.97749955, -0.06565939, -0.98515688, -0.50729114]],
      shape=(1070, 5))

In [36]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'kernel':['rbf','poly','sigmoid','linear'],
            'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(),param_grid,refit= True, verbose = 3, n_jobs= -1)

grid.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [37]:
result=grid.cv_results_
print("The R_score value for best prameter {}".format(grid.best_params_))

The R_score value for best prameter {'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}

In [38]:
table = pd.DataFrame.from_dict(result)

In [39]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.088092,0.003102,0.042706,0.002580,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.037325,0.021048,-0.036168,-0.084435,-0.117458,-0.050867,0.047186,36
1,0.066389,0.001755,0.013280,0.000604,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.018511,0.085272,0.033035,-0.010290,-0.053604,0.014585,0.046089,31
2,0.086644,0.002063,0.017646,0.001386,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.015530,0.084609,0.027106,-0.021105,-0.053763,0.010475,0.046737,34
3,0.071366,0.005696,0.012775,0.001547,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.390629,0.478401,0.431247,0.387305,0.354880,0.408492,0.042537,25
4,0.082137,0.002961,0.040205,0.001795,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.037397,0.021106,-0.036096,-0.084348,-0.117601,-0.050867,0.047232,35
5,0.066561,0.001332,0.012852,0.000609,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.019948,0.084177,0.031529,-0.011743,-0.051330,0.014516,0.045159,32
6,0.090938,0.003495,0.016682,0.000147,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.015867,0.084351,0.026787,-0.021351,-0.053233,0.010484,0.046528,33
7,0.077113,0.005754,0.013235,0.002223,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.390629,0.478401,0.431247,0.387305,0.354880,0.408492,0.042537,25
8,0.084136,0.002401,0.039272,0.001755,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.282882,0.365482,0.289946,0.246873,0.215599,0.280156,0.050317,27
9,0.074814,0.004152,0.012345,0.000397,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.540280,0.610001,0.573841,0.556588,0.459042,0.547950,0.050117,22
10,0.089700,0.003257,0.016719,0.000275,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.479965,0.536934,0.507258,0.461129,0.440349,0.485127,0.034004,24
11,0.076979,0.003980,0.012187,0.000596,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.585412,0.629734,0.617429,0.584651,0.552153,0.593876,0.027343,19
12,0.082211,0.002061,0.039840,0.001530,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.282276,0.365919,0.290460,0.247487,0.214634,0.280155,0.050649,28
13,0.073824,0.002120,0.012636,0.000517,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.544403,0.607290,0.570094,0.553578,0.465910,0.548255,0.046445,21
14,0.095527,0.004362,0.018104,0.002240,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.481860,0.537004,0.507621,0.460342,0.440683,0.485502,0.034049,23
15,0.080970,0.004122,0.012242,0.000558,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.585412,0.629734,0.617429,0.584651,0.552153,0.593876,0.027343,19
16,0.098280,0.004598,0.041917,0.002490,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.769052,0.780447,0.762308,0.767010,0.691774,0.754118,0.031737,12
17,0.106306,0.010144,0.014589,0.002022,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.825149,0.819834,0.811681,0.836272,0.740817,0.806751,0.033920,8
18,0.115396,0.003828,0.020464,0.001961,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.306842,0.216677,0.325978,0.160679,0.309872,0.264010,0.064336,30
19,0.108899,0.004823,0.013967,0.002589,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.651795,0.629307,0.637008,0.650704,0.601740,0.634111,0.018262,13
20,0.122390,0.005264,0.043755,0.001786,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.768851,0.780630,0.762558,0.767361,0.691206,0.754121,0.032014,11
21,0.104656,0.006286,0.012828,0.000343,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.826301,0.819682,0.811392,0.836006,0.742592,0.807195,0.033293,7
22,0.100162,0.005249,0.017615,0.001215,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.310695,0.222521,0.334635,0.173480,0.301074,0.268481,0.060594,29
23,0.105602,0.009551,0.012741,0.000874,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.651795,0.629307,0.637008,0.650704,0.601740,0.634111,0.018262,13
24,0.110540,0.003936,0.042909,0.003272,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.828351,0.814160,0.797293,0.823797,0.735907,0.799902,0.033722,9
25,0.183587,0.047970,0.014059,0.001196,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.839418,0.822365,0.815980,0.839691,0.750080,0.813507,0.033059,4
26,0.107917,0.002977,0.017897,0.000933,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.451430,-0.745829,-0.639843,-0.989296,-0.468395,-0.658958,0.198200,37
27,0.160215,0.050552,0.011989,0.000368,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.657836,0.624504,0.632004,0.649113,0.597156,0.632123,0.021121,15
28,0.109287,0.002741,0.039837,0.002247,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.828193,0.814198,0.797419,0.823872,0.735771,0.799891,0.033759,10
29,0.197168,0.028157,0.013261,0.000915,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.839371,0.822322,0.815970,0.839763,0.750572,0.813600,0.032872,3
30,0.105607,0.005257,0.016912,0.000720,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.472104,-1.109682,-0.615668,-0.962824,-0.525840,-0.737223,0.252732,38
31,0.185276,0.060080,0.013387,0.001047,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.657836,0.624504,0.632004,0.649113,0.597156,0.632123,0.021121,15
32,0.124881,0.004525,0.040551,0.002443,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.838764,0.823122,0.805058,0.836063,0.741767,0.808955,0.035647,6
33,0.346281,0.138575,0.013670,0.001283,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.840456,0.821812,0.813557,0.838468,0.754565,0.813771,0.031280,2
34,0.108663,0.010857,0.017738,0.001673,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.789185,-3.304977,-2.288641,-1.806489,-1.794049,-2.196668,0.586036,39
35,0.156662,0.053951,0.011780,0.000645,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.658338,0.624508,0.631999,0.646221,0.597151,0.631644,0.020813,17
36,0.119897,0.007783,0.042899,0.003528,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.838645,0.823178,0.805177,0.836119,0.741674,0.808959,0.035673,5
37,0.278561,0.037744,0.013203,0.000734,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.840472,0.821813,0.813520,0.838583,0.754680,0.813814,0.031257,1
38,0.105761,0.006045,0.019357,0.003087,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.843270,-2.497666,-2.236821,-2.604137,-1.865146,-2.209408,0.313761,40
39,0.152427,0.054525,0.011167,0.001982,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.658338,0.624508,0.631999,0.646221,0.597151,0.631644,0.020813,17

In [40]:
age=float(input("Age: "))     
bmi=float(input("BMI: "))
children=int(input("Children: "))
sex_Male=int(input("Sex Male 0 or 1: "))
smoker_yes=int(input("Smoker Yes 0 or 1: "))

Age:  35
BMI:  43
Children:  2
Sex Male 0 or 1:  1
Smoker Yes 0 or 1:  0

In [41]:
Future_Prediction= grid.predict([[age,bmi,children,sex_Male,smoker_yes]])
print("Future Prediction={}".format(Future_Prediction))

Future Prediction=[4738604.21326121]