In [1]:
import pandas as pd

In [2]:
#data collection
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
#data preprocessing
#As we have categorical data as input we have to convert in to binary values.
#State input has nominal data so we have to use one hot encoding, so it uses input field expansion
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [4]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [5]:
dependent=dataset[['charges']]

In [10]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [6]:
#Split the dataset into train and test set 
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.2,random_state=0)

In [19]:
x_train

      age     bmi  children  sex_male  smoker_yes
621    37  34.100         4      True        True
194    18  34.430         0      True       False
240    23  36.670         2     False        True
1168   32  35.200         2      True       False
1192   58  32.395         1     False       False
...   ...     ...       ...       ...         ...
763    27  26.030         0      True       False
835    42  35.970         2      True       False
1216   40  25.080         0      True       False
559    19  35.530         0      True       False
684    33  18.500         1     False       False

[1070 rows x 5 columns]

In [20]:
x_test

      age     bmi  children  sex_male  smoker_yes
578    52  30.200         1      True       False
610    47  29.370         1     False       False
569    48  40.565         2      True        True
1034   61  38.380         0      True       False
198    51  18.050         0     False       False
...   ...     ...       ...       ...         ...
1084   62  30.495         2     False       False
726    41  28.405         1      True       False
1132   57  40.280         0      True       False
725    30  39.050         3     False        True
963    46  24.795         3      True       False

[268 rows x 5 columns]

In [21]:
y_train

          charges
621   40182.24600
194    1137.46970
240   38511.62830
1168   4670.64000
1192  13019.16105
...           ...
763    3070.80870
835    7160.33030
1216   5415.66120
559    1646.42970
684    4766.02200

[1070 rows x 1 columns]

In [22]:
y_test

          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1084  15019.76005
726    6664.68595
1132  20709.02034
725   40932.42950
963    9500.57305

[268 rows x 1 columns]

In [7]:
#Model creation
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [24]:
regressor.coef_

array([[ 2.54952280e+02,  3.20693337e+02,  4.30809389e+02,
        -2.34557931e+01,  2.35890247e+04]])

In [25]:
regressor.intercept_

array([-11901.10455877])

In [8]:
#prediction 
y_pred= regressor.predict(x_test)

In [9]:
#Evaluation
from sklearn.metrics import r2_score
r2score=r2_score(y_test,y_pred)

In [10]:
r2score

0.7978644236809905